apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: mattermost.example.com
    http:
      paths:
      - path: /mattermost-ldap
        backend:
          serviceName: mattermost-ldap
          servicePort: 443
